# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 18:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('plot', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('area', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('HID', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.IntegerField(default=0)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(1, 1), null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('WID', models.AutoField(primary_key=True, serialize=False)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(1, 1), null=True, srid=4326)),
                ('AvgYield', models.DecimalField(decimal_places=4, max_digits=7)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='HID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household'),
        ),
    ]
