# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Rice', max_length=50)),
                ('Year', models.IntegerField()),
                ('season', models.CharField(choices=[('S', 'Summer'), ('W', 'Winter'), ('M', 'Monsoon')], max_length=20)),
                ('FID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yields', models.FloatField(default=0.0)),
                ('measured_date', models.DateField(default=datetime.date.today)),
                ('WID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Well')),
            ],
        ),
    ]
